### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'size'

### ISSUE THREAD

**Issue by 40min** [ahmedbesbes/character-based-cnn#1]
train is always falling even with such kind of file:
"""
SentimentText;Sentiment
aaa;1
bbb;2
ccc;3
"""
Params of running -- just data_path
Packages installed:
numpy==1.16.1
pandas==0.24.1
Pillow==5.4.1
protobuf==3.6.1
python-dateutil==2.8.0
pytz==2018.9
scikit-learn==0.20.2
scipy==1.2.1
six==1.12.0
sklearn==0.0
tensorboardX==1.6
torch==1.0.1.post2
torchvision==0.2.1
tqdm==4.31.1

**Comment by ahmedbesbes** [comment]
Sentiment should be a binary value (0/1)

**Comment by 40min** [comment]
Oh, thanks,  I've spent hours trying to understand before I asked here.
